compile:
	echo "***************  COMPLING  ***************"
	g++ main.cpp ../../src/*.cpp -I../../headers/*.h -o main.exe

run: compile
	echo "***************  RUNNING  ***************"
	./main.exe

clean:
	rm main.exe || clear
	clear